=== migrants-and-the-state/extracted-data/schemas/page-schema-kc-2023.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "afile_id": {
      "type": "string"
    },
    "page_index": {
      "type": "integer"
    },
    "resources": {
      "type": "object",
      "properties": {
        "full_jpg": {
          "type": "string"
        },
        "ocr_txt": {
          "type": "boolean",
          "default": false
        }
      },
      "required": ["full_jpg", "ocr_txt"]
    },
    "fields": {
      "type": "object",
      "properties": {
        "sex": {
          "type": "object",
          "properties": {
            "ms_sex_llm_v1": {
              "type": ["string", "null"],
              "default": null
            }
          }
        },
        "doctype": {
          "type": "object",
          "properties": {
            "ms_doctype_v1": {
              "type": "string"
            }
          },
          "required": ["ms_doctype_v1"]
        },
        "form_title": {
          "type": "object",
          "properties": {
            "ms_form_title_llm_v1": {
              "type": ["string", "null"],
              "default": null
            }
          }
        },
        "is_g325a": {
          "type": "boolean",
          "default": false
        },
        "is_cert_naturalization": {
          "type": "boolean",
          "default": false
        },
        "countries": {
          "type": "object",
          "properties": {
            "ms_countries_nlp_v1": {
              "type": ["array", "null"],
              "items": {
                "type": "string"
              },
              "default": null
            }
          }
        },
        "years": {
          "type": "object",
          "properties": {
            "ms_years_nlp_v1": {
              "type": ["array", "null"],
              "items": {
                "type": "number"
              },
              "default": null
            }
          }
        },
        "certificate_naturalization": {
          "type": "object",
          "properties": {
            "complexion": {
              "type": "object",
              "properties": {
                "complexion_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            },
            "marital_status": {
              "type": "object",
              "properties": {
                "marital_status_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            },
            "year_naturalization": {
              "type": "object",
              "properties": {
                "year_naturalization_llm_v1": {
                  "type": ["number", "null"],
                  "default": null
                }
              }
            },
            "residence_naturlization": {
              "type": "object",
              "properties": {
                "residence_naturlization_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            }
          }
        },
        "g325a": {
          "type": "object",
          "properties": {
            "occupation": {
              "type": "object",
              "properties": {
                "occupation_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            },
            "reason": {
              "type": "object",
              "properties": {
                "reason_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            },
            "nationality": {
              "type": "object",
              "properties": {
                "nationality_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            }
          }
        }
      }
    }
  },
  "required": ["id", "afile_id", "page_index", "resources", "fields"]
}

=== migrants-and-the-state/extracted-data/data/metadata_outputs/A18591348_0021.json
{
    "id": "A18591348",
    "afile_id": "A18591348_0021",
    "page_index": 21,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A18591348_0021/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": null
        },
        "doctype": {
            "ms_doctype_v1": "letter"
        },
        "form_title": {
            "ms_form_title_llm_v1": "U.S. Government Printing Office: 1969 of \u2014337-977"
        },
        "is_g325a": false,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "Canada",
                "Cuba",
                "Mexico",
                "Dominican Republic",
                "Haiti",
                "Netherlands",
                "United States",
                "Bahamas",
                "Barbados",
                "Bermuda",
                "Jamaica"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                1924,
                1969,
                1948,
                1959
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": null
            },
            "reason": {
                "reason_llm_v1": null
            },
            "nationality": {
                "nationality_llm_v1": null
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/metadata_outputs/A21526240_0019.json
{
    "id": "A21526240",
    "afile_id": "A21526240_0019",
    "page_index": 19,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A21526240_0019/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": "female"
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "Application for Adjustment of Status to that of a Lawful Permanent Resident in the Office of Immigration and Naturalization Services Form I-440, Application for Alien Registration ( 23.179; Block II - Information About Alien Beneficiary (Continued."
        },
        "is_g325a": false,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "United States",
                "India"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                1973,
                2023,
                1979,
                1976
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": null
            },
            "reason": {
                "reason_llm_v1": null
            },
            "nationality": {
                "nationality_llm_v1": null
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/metadata_outputs/A21343567_0024.json
{
    "id": "A21343567",
    "afile_id": "A21343567_0024",
    "page_index": 24,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A21343567_0024/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": null
        },
        "doctype": {
            "ms_doctype_v1": "letter"
        },
        "form_title": {
            "ms_form_title_llm_v1": "LOI KHAI HUU TUE THE CUA NGUOI TY NAN XIN NHAP CANH HOA KY, NARA, 8/17/2023"
        },
        "is_g325a": false,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": []
        },
        "years": {
            "ms_years_nlp_v1": [
                2023
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": null
            },
            "reason": {
                "reason_llm_v1": null
            },
            "nationality": {
                "nationality_llm_v1": null
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/pages/A20865114_0076.json
{
    "id": "A20865114",
    "afile_id": "A20865114_0076",
    "page_index": 76,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A20865114_0076/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": "female"
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "BIOGRAPHIC INFORMATION, FORM G-325C ( (9-1-74) Y"
        },
        "is_g325a": false,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "France",
                "Vietnam",
                "United States"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                1971,
                1954,
                1945,
                1955,
                2023,
                1913,
                1976,
                1915,
                1977,
                1950,
                1936
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": null
            },
            "reason": {
                "reason_llm_v1": null
            },
            "nationality": {
                "nationality_llm_v1": null
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/metadata_outputs/A11138471_0026.json
{
    "id": "A11138471",
    "afile_id": "A11138471_0026",
    "page_index": 26,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A11138471_0026/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": "male"
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "APPLICATION FOR IMMIGRANT VISA AND ALIEN REGISTRATION, Form FS-265a (Revised August 1930)"
        },
        "is_g325a": false,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "United States"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                1912,
                1956,
                1905,
                1948,
                1914,
                1952,
                1957,
                1920
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": null
            },
            "reason": {
                "reason_llm_v1": null
            },
            "nationality": {
                "nationality_llm_v1": null
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/metadata_outputs/A21431061_0030.json
{
    "id": "A21431061",
    "afile_id": "A21431061_0030",
    "page_index": 30,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A21431061_0030/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": null
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "Screened by NARA, 9/22/2023, A21-4431-061"
        },
        "is_g325a": false,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "Vietnam"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                2023
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": null
            },
            "reason": {
                "reason_llm_v1": null
            },
            "nationality": {
                "nationality_llm_v1": null
            }
        }
    }
}
