=== migrants-and-the-state/extracted-data/schemas/page-schema-kc-2023.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "afile_id": {
      "type": "string"
    },
    "page_index": {
      "type": "integer"
    },
    "resources": {
      "type": "object",
      "properties": {
        "full_jpg": {
          "type": "string"
        },
        "ocr_txt": {
          "type": "boolean",
          "default": false
        }
      },
      "required": ["full_jpg", "ocr_txt"]
    },
    "fields": {
      "type": "object",
      "properties": {
        "sex": {
          "type": "object",
          "properties": {
            "ms_sex_llm_v1": {
              "type": ["string", "null"],
              "default": null
            }
          }
        },
        "doctype": {
          "type": "object",
          "properties": {
            "ms_doctype_v1": {
              "type": "string"
            }
          },
          "required": ["ms_doctype_v1"]
        },
        "form_title": {
          "type": "object",
          "properties": {
            "ms_form_title_llm_v1": {
              "type": ["string", "null"],
              "default": null
            }
          }
        },
        "is_g325a": {
          "type": "boolean",
          "default": false
        },
        "is_cert_naturalization": {
          "type": "boolean",
          "default": false
        },
        "countries": {
          "type": "object",
          "properties": {
            "ms_countries_nlp_v1": {
              "type": ["array", "null"],
              "items": {
                "type": "string"
              },
              "default": null
            }
          }
        },
        "years": {
          "type": "object",
          "properties": {
            "ms_years_nlp_v1": {
              "type": ["array", "null"],
              "items": {
                "type": "number"
              },
              "default": null
            }
          }
        },
        "certificate_naturalization": {
          "type": "object",
          "properties": {
            "complexion": {
              "type": "object",
              "properties": {
                "complexion_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            },
            "marital_status": {
              "type": "object",
              "properties": {
                "marital_status_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            },
            "year_naturalization": {
              "type": "object",
              "properties": {
                "year_naturalization_llm_v1": {
                  "type": ["number", "null"],
                  "default": null
                }
              }
            },
            "residence_naturlization": {
              "type": "object",
              "properties": {
                "residence_naturlization_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            }
          }
        },
        "g325a": {
          "type": "object",
          "properties": {
            "occupation": {
              "type": "object",
              "properties": {
                "occupation_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            },
            "reason": {
              "type": "object",
              "properties": {
                "reason_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            },
            "nationality": {
              "type": "object",
              "properties": {
                "nationality_llm_v1": {
                  "type": ["string", "null"],
                  "default": null
                }
              }
            }
          }
        }
      }
    }
  },
  "required": ["id", "afile_id", "page_index", "resources", "fields"]
}

=== migrants-and-the-state/extracted-data/data/metadata_outputs/A17195429_0064.json
{
    "id": "A17195429",
    "afile_id": "A17195429_0064",
    "page_index": 64,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A17195429_0064/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": "female"
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "U.S. Department of Justice Application to File Immigration and Naturalization Service Petition for Naturalization, N-4 115-009"
        },
        "is_g325a": false,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "China",
                "United States"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                1969,
                2023,
                1963,
                1915,
                1978
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": null
            },
            "reason": {
                "reason_llm_v1": null
            },
            "nationality": {
                "nationality_llm_v1": null
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/pages/A86927428_0041.json
{
    "id": "A86927428",
    "afile_id": "A86927428_0041",
    "page_index": 41,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A86927428_0041/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": "female"
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "Certification of Translation, 2#26213"
        },
        "is_g325a": false,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "Honduras"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                2004,
                2007,
                2023,
                2008
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": null
            },
            "reason": {
                "reason_llm_v1": null
            },
            "nationality": {
                "nationality_llm_v1": null
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/metadata_outputs/A42733525_0041.json
{
    "id": "A42733525",
    "afile_id": "A42733525_0041",
    "page_index": 41,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A42733525_0041/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": "male"
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "\u5e38\u4f4f\u4eba\u53e3\u767b\u8bb0\u8868, \u67284\u4f9b\u900908 88112"
        },
        "is_g325a": false,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": []
        },
        "years": {
            "ms_years_nlp_v1": [
                2023
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": null
            },
            "reason": {
                "reason_llm_v1": null
            },
            "nationality": {
                "nationality_llm_v1": null
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/pages/A11638538_0020.json
{
    "id": "A11638538",
    "afile_id": "A11638538_0020",
    "page_index": 20,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A11638538_0020/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": "male"
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "BIOGRAPHIC INFORMATION, G-325 ( (Rev. 10-1-82) Y"
        },
        "is_g325a": true,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "Honduras",
                "Belize",
                "United States"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                1971,
                1970,
                1956,
                1960,
                1945,
                1987,
                2023,
                1944,
                1978
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": "[' retired', 'mechanical eng']"
            },
            "reason": {
                "reason_llm_v1": "NATURALIZATION"
            },
            "nationality": {
                "nationality_llm_v1": "Honduras"
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/pages/A14635169_0023.json
{
    "id": "A14635169",
    "afile_id": "A14635169_0023",
    "page_index": 23,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A14635169_0023/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": "male"
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "Biographic Information, G-325A"
        },
        "is_g325a": true,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "China",
                "United States"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                2023,
                1911,
                1982
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": "['n/a']"
            },
            "reason": {
                "reason_llm_v1": "NATURALIZATION"
            },
            "nationality": {
                "nationality_llm_v1": "Chinese"
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/metadata_outputs/A26271163_0123.json
{
    "id": "A26271163",
    "afile_id": "A26271163_0123",
    "page_index": 123,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A26271163_0123/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": null
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "NBC N400 PRINTS, UNITED STATES CITIZENSHIP AND IMMIGRATION SERVICES"
        },
        "is_g325a": false,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "United States"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                1910,
                2011,
                2023
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": null
            },
            "reason": {
                "reason_llm_v1": null
            },
            "nationality": {
                "nationality_llm_v1": null
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/metadata_outputs/A19055851_0055.json
{
    "id": "A19055851",
    "afile_id": "A19055851_0055",
    "page_index": 55,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A19055851_0055/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": "female"
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "United States Department of Justice Immigration and Naturalization Service, G-325A"
        },
        "is_g325a": true,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "Canada",
                "United States",
                "Australia",
                "Pakistan",
                "Germany"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                1949,
                1969,
                1909,
                1934
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": "['butler', ' manager']"
            },
            "reason": {
                "reason_llm_v1": "NATURALIZATION"
            },
            "nationality": {
                "nationality_llm_v1": "So. African"
            }
        }
    }
}

=== migrants-and-the-state/extracted-data/data/metadata_outputs/A42940170_0018.json
{
    "id": "A42940170",
    "afile_id": "A42940170_0018",
    "page_index": 18,
    "resources": {
        "full_jpg": "https://dctn4zjpwgdwdiiy5odjv7o2se0bqgjb.lambda-url.us-east-1.on.aws/iiif/3/og-2023-kc-nara_A42940170_0018/full/max/0/default.jpg",
        "ocr_txt": true
    },
    "fields": {
        "sex": {
            "ms_sex_llm_v1": "male"
        },
        "doctype": {
            "ms_doctype_v1": "form"
        },
        "form_title": {
            "ms_form_title_llm_v1": "Petition for Alien Relative, I-135"
        },
        "is_g325a": false,
        "is_cert_naturalization": false,
        "countries": {
            "ms_countries_nlp_v1": [
                "India"
            ]
        },
        "years": {
            "ms_years_nlp_v1": [
                2023,
                1991
            ]
        },
        "certificate_naturalization": {
            "complexion": {
                "complexion_llm_v1": null
            },
            "marital_status": {
                "marital_status_llm_v1": null
            },
            "year_naturalization": {
                "year_naturalization_llm_v1": NaN
            },
            "residence_naturlization": {
                "residence_naturlization_llm_v1": null
            }
        },
        "g325a": {
            "occupation": {
                "occupation_llm_v1": null
            },
            "reason": {
                "reason_llm_v1": null
            },
            "nationality": {
                "nationality_llm_v1": null
            }
        }
    }
}
